### PR TITLE
CS rule for final classes

### PR DESCRIPTION
**Pull request by michal-tichy-84**
Resolves https://github.com/BrandEmbassy/developers-manifest/issues/741

### CODE REVIEW

**Comment by PetrHeinz** [comment]
TODO:
* [ ] test it on a sufficiently complex codebase (eg. platform-backend / channel-integrations)
* [ ] cover newly found edge cases with tests and fix it
* [ ] when OK, merge it and release new version
* [ ] upgrade to new version in our repos
* [ ] run fixer and be enjoy not doing this manually
* [ ] remove BypassFinal

**Review by PetrHeinz — APPROVED** [review]
Approved as we did it during pair-programming session. Please, @michal-tichy-84. review the commits added.

**Comment by PetrHeinz** [comment]
Seems to work as intended when tested in https://github.com/BrandEmbassy/channel-integrations/pull/711

Could remove some ignored issues in PhpStan, and after the fix, it discovered some new real issues with the code.

**Comment by PetrHeinz** [comment]
Oh, I forgot to remove BypassFinals. Will try that.

(https://github.com/BrandEmbassy/coding-standard/pull/61 should help with not forgetting that)

**Comment by PetrHeinz** [comment]
And we have to apply this rule in our libraries (eg. platform-api-client) before removing the bypass as we are mocking their classes as well...

**Review by dominikvoda — APPROVED** [review]

**Pull request merged**
